### ISSUE TITLE
Plugin should set 'commentstring' in vim

### ISSUE THREAD

**Issue by malteneuss** [jvirtanen/vim-octave#1]
Many people use commenting plugins such as [tComment](https://github.com/vim-scripts/tComment), which use vim's build-in variable 'commentstring' to know which symbol to use for comments. However there is nothing defined for files with FileType 'octave'. So i suggest to include

```
autocmd! FileType octave setlocal commentstring=%%\ %s
```

in this plugin.

**Comment by jvirtanen** [comment]
Sounds like a great idea to me, @malteneuss. I, however, maintain this repository merely as a mirror of [octave.vim](http://www.vim.org/scripts/script.php?script_id=3600). I suggest you get in touch with the upstream maintainer, Rik, regarding this matter (see the link for the contact information). I'm then very happy to pull the latest changes as soon as they become available in the upstream.

**Comment by malteneuss** [comment]
I wrote him an Email; he'll think about it.

**Comment by malteneuss** [comment]
Rik won't add it.
