### ISSUE TITLE
Breakpoints

### ISSUE THREAD

**Issue by scientist1642** [jvirtanen/vim-octave#2]
Hi Jussi,
Does it have any support for breakpoints? or in general how do you put them when using vim.

**Comment by jvirtanen** [comment]
Hi Zura,

These are just syntax highlighting rules for GNU Octave and do not contain advanced IDE-like features, such as debugging support. (As a matter of fact, this is just a GitHub mirror of Rik's [octave.vim](http://www.vim.org/scripts/script.php?script_id=3600).)

I'm unfortunately myself unfamiliar with GNU Octave's debugger, so I can only suggest checking out the [help-octave](https://lists.gnu.org/mailman/listinfo/help-octave) mailing list for help. Good luck!
