### ISSUE TITLE
Upstream has a newer version with support for 4.2.0

### ISSUE THREAD

**Issue by JoshDoug** [jvirtanen/vim-octave#3]
Thanks for maintaining this mirror, very useful.

The upstream version at http://www.vim.org/scripts/script.php?script_id=3600 lists a newer version with support for 4.2.0 functions etc

Could this repo be updated?
Thanks again!

**Comment by jvirtanen** [comment]
Thanks for the tip, @JoshDoug! I just imported 4.2.0 into the repository.
